# FROM golang

# WORKDIR /app
# ADD meu_go.go /app
# RUN go mod init teste
# RUN go build -o meugo
# ENTRYPOINT ./meugo

# FROM golang

# WORKDIR /app
# ADD . .
# RUN go mod init v1
# RUN go mod tidy
# RUN go build -o meugo
# ENTRYPOINT ./meugo

# FROM debian

# WORKDIR /app
# ADD . /app
# RUN clang hello.c -o hello
# ENTRYPOINT ["./hello"]